services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./.env
    volumes:
      - .:/app
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U postgres
      interval: 2s
      retries: 10
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  worker:
    build: .
    command: rq worker --url ${REDIS_URL} emails
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./.env  
volumes:
  postgres_data:
